# Generated by Django 5.0.1 on 2024-03-27 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(default="Default Product Name", max_length=255),
                ),
                ("image_path", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                ("quantity", models.IntegerField(default=1)),
                ("formulation", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("isDeleted", models.BooleanField(default=False)),
            ],
        ),
    ]
